chpladmin/chpl-data-model

- README.md
Was pointing to the wrong location.
> Update git-clone url

- ocd-1087.sql
Forgot to give permission on the sequence. This file has to be run and then the ocd-* file with like 5 tasks listed out has to be run again also.
> OCD-1087: add permissions for sequence

- v-next.sql
When running this script using `psql -Uopenchpl -f v-next.sql` the non-namespaced temp tables get automatically put into the user's namespace, which means the temp tables overwrite the real ones. I don't know how this script could have been run successfully for as long as it seems to have been
> OCD-1071: Renamed temp tables to avoid collisions

- v-next.sql
> OCD-1127: add new cp status to view for decert date calc

- maint/users.sql
No RELEASE_NOTES, as this isn't really anything the public would care about
> chore: update compromised password

- RELEASE_NOTES.md
- ocd-1889.sql
- ocd-1935.sql
Going to DEV only; prep for Jan release
> OCD-1935: Marked deprecated upload templates as deleted

- v-next.sql
This fixes issues #2 and #3 found by Ashwini on 7/2
OCD-1503
> Fixed sql script for f(3)

- PENDING_PENDING_RELEASE_NOTES.md
- dev/openchpl_audit.sql
- dev/openchpl_data-model.sql
- dev/openchpl_views.sql
- v-dev.sql
> Updated data model with table and view to support OCD-2275

- v-dev.sql
> Add call to grant_all script after function/trigger added

- PENDING_PENDING_RELEASE_NOTES.md
- RELEASE_NOTES.md
- dev/openchpl_views.sql
- v-dev.sql
> Add Developer Status to search results view

- PENDING_PENDING_RELEASE_NOTES.md
- dev/openchpl_data-model.sql
- v-dev.sql
> Add reason column to questionable_activity_developer table

- PENDING_OOC_RELEASE_NOTES.md
- RELEASE_NOTES.md
- hot-fix.sql
> Mark erroneously uploaded Listing as deleted

- dev/openchpl_preload.sql
- dev/openchpl_views.sql
- v-dev.sql
> refactor: remove unused references to ATLs

- dev/openchpl_views.sql
- v-next.sql
> fix: remove ref to testing_lab_id from function

- ocd-2655.sql
- v-next.sql
> feat: add/populate new column pending_surveillance.user_permission_id

- PENDING_RELEASE_NOTES.md
- v-next.sql
> fix: remove insert into data_model_version statements

- maint/create-user.sql
> feat: add ability to create users with ATL access

- STAGED_RELEASE_NOTES.md
- dev/openchpl_preload.sql
- ocd-2825.sql
- v-next.sql
> fix: mark OBE status as deleted

- dev/openchpl_views.sql
> fix: use "rank" instead of max date when selecting most recent muu

- dev/openchpl_views.sql
> fix: use 'row_number' instead of 'rank' for meaningful_use_user

- dev/openchpl_views.sql
> fix: update partition by clause for MUU sub query in views

- PENDING_RELEASE_NOTES.md
- RELEASE_NOTES.md
- v-next.sql
> refactor: remove obsolete tables

- dev/openchpl_preload.sql
- ocd-2912.sql
- v-next.sql
> OCD-2912 - Add basic complaint 

- ocd-2917.sql
- v-next.sql
> fix: remove deployed files

- maint/dump.sh
- maint/load.sh
> feat: support ports on scripts

- dev/openchpl_audit.sql
- dev/openchpl_data-model.sql
- dev/openchpl_preload.sql
- ocd-2912.sql
fix: rename complaint_type -> complainant_type
> OCD-2912 - Create a basic complaint

- dev/openchpl_soft-delete.sql
feat: delete complaint_surveilllance_map recs when surveillance is del
> OCD-2915 - Associate a complaint with surveillance

- dev/openchpl_preload.sql
- ocd-3016.sql
- v-next.sql
qa: reset activity concept sequence and add COMPLAINT, if necessary
OCD-3016
>  fix: add activity concept for type COMPLAINT

- dev/openchpl_preload.sql
- ocd-3015.sql
- v-next.sql
> data: add quarterly report and annual report activity types

- ocd-3080.sql
- v-next.sql
> data: Remove mistakenly uploaded listings

- ocd-3018.sql
- v-next.sql
> data: Create new address for addresses that are re-used by orgs

- dev/openchpl_audit.sql
- dev/openchpl_data-model.sql
- dev/openchpl_preload.sql
- ocd-2158.sql
- v-next.sql
[#OCD-2158]
This is much of a work in progress PR, but does function, and provides the base for a few other tickets
> feat: add ROLE_DEVELOPER

- ocd-3018.sql
> qa: update sql script to fix sql error

- commitlint.config.js
- v-next.sql
> build: insert the g1/g2 values

- dev/openchpl_audit.sql
- dev/openchpl_preload.sql
- ocd-2178.sql
- v-next.sql
> data: Log all 2014 Listing Edit activity as questionable

- maint/dump.sh
> ci: don't migrate FF4j flags

- RELEASE_NOTES.md
> docs: reconcile RELEASE_NOTES

- dev/openchpl_views.sql
> feat: Add mapping view between developers and acbs

- dev/openchpl_audit.sql
- dev/openchpl_data-model.sql
- dev/openchpl_preload.sql
- ocd-3116.sql
- v-next.sql
[#OCD-3116]
BREAKING_CHANGE: removes column from complaint table, as well as entire table
> OCD-3116 - feat!: Remove Complaint Status Type data

- dev/openchpl_preload.sql
> OCD-3235: Add new test tool via quartz job 

- dev/openchpl_data-model.sql
- dev/openchpl_views.sql
- ocd-3234.sql
- v-next.sql
> [#OCD-3234] Add Self-Developer element to Developer information

- ocd-3292.sql
- v-next.sql
> OCD-3292 - add new questionable activity triggers for old criteria and ICS
